### ISSUE TITLE
Unprotected path

### ISSUE THREAD

**Issue by kahwooi** [andela-thomas/express-acl#19]
Is there anywhere to omit certain route from authorization. For example I would not want protect the /auth path.

Can I do like:

`app.use(acl.authorize).unless({path: ['/auth']}));
`

**Comment by andela-thomas** [comment]
@kahwooi That has not been implemented yet, but I will be glad if you we could work together to achieve that.

**Comment by kahwooi** [comment]
Can use [express-unless](https://github.com/jfromaniello/express-unless) in authorize middleware?

**Comment by andela-thomas** [comment]
Let me look into it and see how well it fits into my implementation to ascertain the best approach

**Comment by kahwooi** [comment]
@andela-thomas I can do this in my code:

```
var unless = require('express-unless');

// ACL middleware
var aclAuth = acl.authorize;
aclAuth.unless = unless;
app.use(aclAuth.unless({path: ['/users/auth']}));
```

**Comment by andela-thomas** [comment]
@kahwooi thanks for the insight, I will definitely plug it into the package.

**Comment by andela-thomas** [comment]
@kahwooi I have included the unless package, to the authorize middlware. Now you can use it as
```js

app.use(acl.authorize.unless({path:['/auth']));

```
Although this changes may not reflect on the npm package for now. Thanks for your contribution

**Comment by kahwooi** [comment]
Just got it from dev branch, it is working great. Thanks!
