### ISSUE TITLE
Changing error message?

### ISSUE THREAD

**Issue by kahwooi** [andela-thomas/express-acl#56]
How can I change the error message for 403 forbidden? 

`{"success":"error","message":"Access denied"}`

I tried this in express app, but the above message get return before hitting the below code:

```
app.use(function(err, req, res, next) {
  res.status(err.status || 403);
  res.status(403).send(err.message);
  next(err);
});
```

**Comment by andela-thomas** [comment]
@kahwoo At the moment we do not have a way to customise error messages for our module. However, it is something we are looking at in our next iteration. Currently, we use this function below to return error JSON
```js
deny: function(res, status, customMessage) {
  var message = customMessage ? customMessage : 'Unauthorized access';
  return res.status(status)
    .send({
      status: 'Access denied',
      success: false,
      message: message
    });
}
```
This only enables us to send custom message depending on where in occurs e.g for missing role or policy. We have no API that can enable one to modify the error message or the JSON response entirely.

If this is something you will be interested in working on I will welcome a PR.

Thank you

**Comment by grahamb** [comment]
Is this something that is being actively worked on? I'm evaluating this for use in a project that already uses [`express-boom`](https://github.com/scottcorgan/express-boom) for responses; I'd love to be able to override the `deny` function when calling `acl.config()` (or even switch to use `express-boom` as the default?).

**Comment by nyambati** [comment]
@grahamb  We were able to provide a way to override error response for `403`. This happens when the user has no access to the requested resource. Below is the current solution on the current release.

```js
const acl = require('express-acl');

let configObject = {
    filename:'acl.json',
    path:'config'
};

let responseObject = {
  status: 'Access Denied',
  message: 'You are not authorized to access this resource'
};

acl.config(configObject, responseObject);
```
I hope this will be able to provide the solution you are looking for. If you need to discuss more on this, we can sync to that we can find a solution that works for you.
