### ISSUE TITLE
Permission check API

### ISSUE THREAD

**Issue by kahwooi** [andela-thomas/express-acl#58]
Is there any API or function that I can use to check if the user has the right to access the page before making API request? 

For example, I have a SPA, it can be written on Angular, React or Vuejs. To prevent a user from accessing a page to POST a new sales, I would like to request an API call to my server to check if the user has permission to the page, so that I can disable the page from loading.

**Comment by andela-thomas** [comment]
@kahwooi 
This module does not have such method or API as it is basically a middleware between the client and your resources. It will only allow traffic to endpoints that have been allowed in your configuration. When you make a request to an Unauthorised endpoint, you will get a JSON response as below.

```json
{
  "status": "Access denied",
  "success": false,
  "message": "Unautorised Access"
}
```

You can use this JSON object to disable rendering a view. Frameworks like Angular provides hooks that can tap into to render a view only when certain conditions are fulfilled e.g [ui-router resolve](https://github.com/angular-ui/ui-router/wiki#resolve).

Based on your scenario I would recommend you use roles attached to each user to achieve this e.g

```js
function renderSalesView(user) {
  let allowed = ['admin', 'sales'];
  return (allowed.includes(user.role)) ? true : false;
}

```
You can decide to render the new sales page only when the method returns `true`. With this you can achieve the same results without making any request to your server.
